# Generated by Django 4.2.2 on 2023-06-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('engine', models.CharField(max_length=50, verbose_name='харрактеристики двигателя')),
                ('gear_type', models.CharField(max_length=50, verbose_name='какая КПП')),
                ('type', models.CharField(max_length=50, verbose_name='тип кузова')),
                ('type_drive_unit', models.CharField(max_length=50, verbose_name='какой привод')),
                ('color', models.CharField(max_length=50, verbose_name='цвет авто')),
                ('price', models.CharField(max_length=50, verbose_name='цена')),
                ('year', models.CharField(max_length=50, verbose_name='год')),
            ],
        ),
    ]
