# Generated by Django 4.2.2 on 2023-06-22 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('engine_power', models.IntegerField(blank=True, null=True, verbose_name='мощность двигателя')),
                ('engine_volume', models.FloatField(blank=True, null=True, verbose_name='обьем двигателя')),
                ('engine_type', models.CharField(max_length=50, verbose_name='какое топливо')),
                ('gear_type', models.CharField(max_length=50, verbose_name='какая КПП')),
                ('type', models.CharField(max_length=50, verbose_name='тип кузова')),
                ('type_drive_unit', models.CharField(max_length=50, verbose_name='какой привод')),
                ('color', models.CharField(max_length=50, verbose_name='цвет авто')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='цена')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='год')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='изображение')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
