# Generated by Django 4.2.2 on 2023-06-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='engine',
        ),
        migrations.AddField(
            model_name='car',
            name='engine_power',
            field=models.IntegerField(blank=True, null=True, verbose_name='мощность двигателя'),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_type',
            field=models.CharField(default='sd', max_length=50, verbose_name='какое топливо'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='engine_volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='обьем двигателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='год'),
        ),
    ]
