# Generated by Django 4.2.2 on 2023-06-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_engine_car_engine_power_car_engine_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine_volume',
            field=models.FloatField(blank=True, null=True, verbose_name='обьем двигателя'),
        ),
    ]
